import type {
  Store,
  CourseCategory,
  PricingRule,
  Course,
  User,
  RefundRequest,
  StoreMetrics,
  CoachStats,
  Booking,
  Message,
  MessageVoucher,
  WaitingQueue,
} from '../types';
import { getDefaultPricingRules } from './price';

export function generateId(): string {
  return Math.random().toString(36).substring(2, 11);
}

export const initialStores: Store[] = [
  { id: 's1', name: 'FitPro 旗舰店', address: '南京路88号', city: '上海' },
  { id: 's2', name: 'FitPro 朝阳店', address: '朝阳路168号', city: '北京' },
  { id: 's3', name: 'FitPro 天河店', address: '天河路200号', city: '广州' },
  { id: 's4', name: 'FitPro 南山店', address: '科技园路50号', city: '深圳' },
];

export const initialCategories: CourseCategory[] = [
  { id: 'c1', name: '动感单车', icon: 'bike', description: '高强度有氧燃脂', basePrice: 88, color: '#FF5E1A' },
  { id: 'c2', name: '瑜伽', icon: 'flower2', description: '身心放松塑形', basePrice: 128, color: '#00C48C' },
  { id: 'c3', name: '力量训练', icon: 'dumbbell', description: '肌群强化训练', basePrice: 158, color: '#3B82F6' },
  { id: 'c4', name: 'HIIT', icon: 'flame', description: '高强度间歇训练', basePrice: 98, color: '#FF4757' },
  { id: 'c5', name: '普拉提', icon: 'activity', description: '核心控制力训练', basePrice: 148, color: '#A855F7' },
];

export const initialPricingRules: PricingRule[] = getDefaultPricingRules();

export const mockUsers: User[] = [
  { id: 'm1', role: 'member', name: '张小明', phone: '13800000001', password: '123456', storeId: 's1', memberLevel: 'gold' },
  { id: 'm2', role: 'member', name: '李思思', phone: '13800000002', password: '123456', storeId: 's1', memberLevel: 'silver' },
  { id: 'm3', role: 'member', name: '王大力', phone: '13800000003', password: '123456', storeId: 's2', memberLevel: 'diamond' },
  { id: 'm4', role: 'member', name: '赵小美', phone: '13800000004', password: '123456', storeId: 's3', memberLevel: 'normal' },
  { id: 'm5', role: 'member', name: '刘强', phone: '13800000005', password: '123456', storeId: 's4', memberLevel: 'gold' },
  { id: 'coach1', role: 'coach', name: '陈教练', phone: '13900000001', password: '123456', storeId: 's1' },
  { id: 'coach2', role: 'coach', name: '林教练', phone: '13900000002', password: '123456', storeId: 's1' },
  { id: 'coach3', role: 'coach', name: '黄教练', phone: '13900000003', password: '123456', storeId: 's2' },
  { id: 'coach4', role: 'coach', name: '周教练', phone: '13900000004', password: '123456', storeId: 's3' },
  { id: 'coach5', role: 'coach', name: '吴教练', phone: '13900000005', password: '123456', storeId: 's4' },
  { id: 'manager1', role: 'manager', name: '运营经理-孙', phone: '13700000001', password: '123456' },
  { id: 'owner1', role: 'owner', name: '店长-钱', phone: '13600000001', password: '123456' },
];

export const initialBookings: Booking[] = [
  {
    id: 'b1',
    memberId: 'm1',
    courseId: 'course1',
    status: 'booked',
    price: 88,
    discountRate: 0.8,
    actualPrice: 70.4,
    bookedAt: '2026-06-05T10:30:00Z',
  },
  {
    id: 'b2',
    memberId: 'm1',
    courseId: 'course3',
    status: 'booked',
    price: 158,
    discountRate: 0.8,
    actualPrice: 126.4,
    bookedAt: '2026-06-05T11:00:00Z',
  },
  {
    id: 'b3',
    memberId: 'm2',
    courseId: 'course2',
    status: 'waiting',
    price: 128,
    discountRate: 0.9,
    actualPrice: 115.2,
    bookedAt: '2026-06-06T09:00:00Z',
  },
  {
    id: 'b4',
    memberId: 'm3',
    courseId: 'course4',
    status: 'booked',
    price: 98,
    discountRate: 0.65,
    actualPrice: 63.7,
    bookedAt: '2026-06-06T14:20:00Z',
  },
  {
    id: 'b5',
    memberId: 'm4',
    courseId: 'course5',
    status: 'booked',
    price: 148,
    discountRate: 1,
    actualPrice: 148,
    bookedAt: '2026-06-06T16:45:00Z',
  },
  {
    id: 'b6',
    memberId: 'm1',
    courseId: 'course8',
    status: 'completed',
    price: 88,
    discountRate: 0.8,
    actualPrice: 70.4,
    bookedAt: '2026-06-04T09:00:00Z',
    attendance: true,
    trainingReport: '本节课完成度良好，心率保持在燃脂区间，建议下次增加阻力档位。',
  },
  {
    id: 'b7',
    memberId: 'm5',
    courseId: 'course7',
    status: 'booked',
    price: 158,
    discountRate: 0.8,
    actualPrice: 126.4,
    bookedAt: '2026-06-06T20:00:00Z',
  },
];

const bookingVoucher = (bookingId: string, amount?: number): MessageVoucher => ({
  type: 'booking',
  bookingId,
  amount,
  issuedAt: new Date().toISOString(),
  code: `BK${Date.now()}${Math.floor(Math.random() * 1000)}`,
});

export const initialWaitingQueues: WaitingQueue[] = [
  {
    courseId: 'course2',
    members: [
      { memberId: 'm1', joinedAt: '2026-06-05T11:00:00Z' },
      { memberId: 'm2', joinedAt: '2026-06-05T12:30:00Z' },
    ],
  },
];

export const initialMessages: Message[] = [
  {
    id: 'msg1',
    userId: 'm1',
    role: 'member',
    type: 'booking_success',
    title: '预约成功',
    content: '您已成功预约「晨间燃脂动感单车」课程，上课时间 06月08日 07:00-08:00，请准时到店。',
    relatedId: 'b1',
    relatedType: 'booking',
    read: false,
    createdAt: '2026-06-05T10:30:00Z',
    hasVoucher: true,
    voucher: bookingVoucher('b1', 70.4),
  },
  {
    id: 'msg2',
    userId: 'm1',
    role: 'member',
    type: 'course_reminder',
    title: '课程提醒',
    content: '您预约的「下肢力量强化」课程将在2小时后开始，请提前15分钟到店热身。',
    relatedId: 'course3',
    relatedType: 'course',
    read: false,
    createdAt: '2026-06-07T16:30:00Z',
    hasVoucher: false,
  },
  {
    id: 'msg3',
    userId: 'm2',
    role: 'member',
    type: 'booking_success',
    title: '候补排队中',
    content: '「午间舒缓瑜伽」课程已满员，您已进入候补队列，当前排位第1位，有空位将自动补位。',
    relatedId: 'b3',
    relatedType: 'booking',
    read: true,
    createdAt: '2026-06-06T09:00:00Z',
    hasVoucher: false,
  },
  {
    id: 'msg4',
    userId: 'm1',
    role: 'member',
    type: 'attendance_record',
    title: '出勤记录已生成',
    content: '您的「动感单车竞速」课程出勤已记录，教练已上传训练报告，请查收。',
    relatedId: 'b6',
    relatedType: 'booking',
    read: true,
    createdAt: '2026-06-06T20:10:00Z',
    hasVoucher: true,
    voucher: {
      type: 'attendance',
      bookingId: 'b6',
      issuedAt: '2026-06-06T20:10:00Z',
      code: 'AT20260606001',
    },
  },
  {
    id: 'msg5',
    userId: 'm3',
    role: 'member',
    type: 'booking_success',
    title: '预约成功',
    content: '您已成功预约「HIIT燃脂挑战」课程，上课时间 06月09日 19:00-20:00。',
    relatedId: 'b4',
    relatedType: 'booking',
    read: false,
    createdAt: '2026-06-06T14:20:00Z',
    hasVoucher: true,
    voucher: bookingVoucher('b4', 63.7),
  },
  {
    id: 'msg6',
    userId: 'manager1',
    role: 'manager',
    type: 'refund_request',
    title: '新退款申请待审批',
    content: '会员张小明提交了退款申请，请及时处理。',
    relatedId: 'r1',
    relatedType: 'refund',
    read: false,
    createdAt: '2026-06-07T08:00:00Z',
    hasVoucher: false,
  },
  {
    id: 'msg7',
    userId: 'coach1',
    role: 'coach',
    type: 'course_reminder',
    title: '课程即将开始',
    content: '您的「下肢力量强化」课程将在今天 18:30 开始，请提前准备。',
    relatedId: 'course3',
    relatedType: 'course',
    read: false,
    createdAt: '2026-06-07T15:00:00Z',
    hasVoucher: false,
  },
  {
    id: 'msg8',
    userId: 'owner1',
    role: 'owner',
    type: 'attendance_record',
    title: '月度运营数据已更新',
    content: '6月门店运营数据看板已更新，请注意查看。',
    read: false,
    createdAt: '2026-06-07T06:00:00Z',
    hasVoucher: false,
  },
];

export const initialRefundRequests: RefundRequest[] = [
  {
    id: 'r1',
    bookingId: 'b1',
    memberId: 'm1',
    totalSessions: 20,
    completedSessions: 5,
    refundRatio: 0.75,
    paidAmount: 1599,
    refundAmount: 1199,
    status: 'pending',
    reason: '工作调动，无法继续上课',
    createdAt: '2025-06-01T10:30:00Z',
  },
  {
    id: 'r2',
    bookingId: 'b2',
    memberId: 'm2',
    totalSessions: 12,
    completedSessions: 2,
    refundRatio: 0.83,
    paidAmount: 899,
    refundAmount: 749,
    status: 'pending',
    reason: '身体原因，医生建议休息',
    createdAt: '2025-06-03T14:20:00Z',
  },
  {
    id: 'r3',
    bookingId: 'b3',
    memberId: 'm1',
    totalSessions: 30,
    completedSessions: 10,
    refundRatio: 0.67,
    paidAmount: 2999,
    refundAmount: 1999,
    status: 'pending',
    reason: '对课程内容不满意',
    createdAt: '2025-06-05T09:15:00Z',
  },
];

export const initialMetrics: StoreMetrics[] = [
  {
    storeId: 's1',
    month: '2025-06',
    bookingRate: 87.5,
    churnRate: 3.2,
    avgSatisfaction: 4.7,
    totalRevenue: 128500,
    activeMembers: 856,
  },
  {
    storeId: 's2',
    month: '2025-06',
    bookingRate: 82.3,
    churnRate: 4.1,
    avgSatisfaction: 4.5,
    totalRevenue: 98700,
    activeMembers: 642,
  },
  {
    storeId: 's3',
    month: '2025-06',
    bookingRate: 90.1,
    churnRate: 2.8,
    avgSatisfaction: 4.8,
    totalRevenue: 156300,
    activeMembers: 1023,
  },
  {
    storeId: 's4',
    month: '2025-06',
    bookingRate: 78.6,
    churnRate: 5.2,
    avgSatisfaction: 4.3,
    totalRevenue: 76800,
    activeMembers: 512,
  },
];

export const initialCoachRankings: CoachStats[] = [
  {
    coachId: 'coach1',
    month: '2025-06',
    totalCourses: 48,
    consumedCourses: 45,
    consumptionRate: 93.75,
    avgSatisfaction: 4.9,
  },
  {
    coachId: 'coach2',
    month: '2025-06',
    totalCourses: 52,
    consumedCourses: 48,
    consumptionRate: 92.31,
    avgSatisfaction: 4.8,
  },
];

export function getInitialCourses(coachId: string = 'coach1'): Course[] {
  const today = new Date();
  const formatDate = (d: Date) => {
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    return `${y}-${m}-${day}`;
  };

  const addDays = (d: Date, n: number) => {
    const nd = new Date(d);
    nd.setDate(nd.getDate() + n);
    return nd;
  };

  return [
    {
      id: 'course1',
      categoryId: 'c1',
      coachId,
      storeId: 's1',
      title: '晨间燃脂动感单车',
      date: formatDate(addDays(today, 1)),
      startTime: '07:00',
      endTime: '08:00',
      capacity: 20,
      bookedCount: 15,
      price: 88,
      status: 'scheduled',
      description: '清晨高强度有氧训练，快速燃烧脂肪，开启活力一天。',
    },
    {
      id: 'course2',
      categoryId: 'c2',
      coachId: 'coach2',
      storeId: 's1',
      title: '午间舒缓瑜伽',
      date: formatDate(addDays(today, 1)),
      startTime: '12:30',
      endTime: '13:30',
      capacity: 15,
      bookedCount: 15,
      price: 128,
      status: 'scheduled',
      description: '工作间隙放松身心，舒缓肩颈压力，提升专注力。',
    },
    {
      id: 'course3',
      categoryId: 'c3',
      coachId,
      storeId: 's1',
      title: '下肢力量强化',
      date: formatDate(addDays(today, 1)),
      startTime: '18:30',
      endTime: '19:30',
      capacity: 12,
      bookedCount: 8,
      price: 158,
      status: 'scheduled',
      description: '深蹲、硬拉、箭步蹲，全方位打造强壮下肢。',
    },
    {
      id: 'course4',
      categoryId: 'c4',
      coachId: 'coach3',
      storeId: 's2',
      title: 'HIIT燃脂挑战',
      date: formatDate(addDays(today, 2)),
      startTime: '19:00',
      endTime: '20:00',
      capacity: 25,
      bookedCount: 20,
      price: 98,
      status: 'scheduled',
      description: '45分钟高强度间歇训练，挑战你的极限。',
    },
    {
      id: 'course5',
      categoryId: 'c5',
      coachId: 'coach4',
      storeId: 's3',
      title: '普拉提核心训练',
      date: formatDate(addDays(today, 2)),
      startTime: '10:00',
      endTime: '11:00',
      capacity: 10,
      bookedCount: 6,
      price: 148,
      status: 'scheduled',
      description: '强化核心肌群，改善体态，提升身体控制能力。',
    },
    {
      id: 'course6',
      categoryId: 'c2',
      coachId: 'coach5',
      storeId: 's4',
      title: '流瑜伽进阶',
      date: formatDate(addDays(today, 3)),
      startTime: '09:00',
      endTime: '10:30',
      capacity: 12,
      bookedCount: 5,
      price: 128,
      status: 'scheduled',
      description: '连贯体式流动，配合呼吸，深度拉伸与力量结合。',
    },
    {
      id: 'course7',
      categoryId: 'c3',
      coachId: 'coach2',
      storeId: 's1',
      title: '上肢力量训练',
      date: formatDate(today),
      startTime: '18:00',
      endTime: '19:00',
      capacity: 12,
      bookedCount: 10,
      price: 158,
      status: 'ongoing',
      description: '胸部、背部、手臂全方位训练。',
    },
    {
      id: 'course8',
      categoryId: 'c1',
      coachId: 'coach3',
      storeId: 's2',
      title: '动感单车竞速',
      date: formatDate(addDays(today, -1)),
      startTime: '19:00',
      endTime: '20:00',
      capacity: 20,
      bookedCount: 18,
      price: 88,
      status: 'completed',
      description: '模拟山地竞速，高强度心肺训练。',
    },
  ];
}

export const initialCourses: Course[] = getInitialCourses();
